schma 작성
DrugStore-devcourse/drugstore pull request #2
Opened 2023-05-02 09:04 UTC by pjw74

2023-05-02 09:07 UTC, pjw74 commented
확인해주세요~ 창민님

2023-05-02 10:38 UTC, pstar314 requested changes
필드명 영어, class Meta, verbose_name 작성 부탁드립니다!

2023-05-03 05:02 UTC, gracia10 requested changes

2023-05-03 05:54 UTC, pjw74 commented
주요 변경 사항
– Drug 모델 생성

2023-05-03 05:57 UTC, gracia10 commented
디비 테이블 명칭은 복수형으로 나오도록 수정했습니다  
정우님, github로 진행한거라 local에는 반영안되어 있을테니 pull 부탁드려요

창민님 요청사항도 반영되어 있어서 merge 진행하겠습니다
고생하셨습니다

2023-05-03 05:57 UTC, merged