Feature/crawling article
DrugStore-devcourse/drugstore pull request #6
Opened 2023-05-03 09:28 UTC by HyeM207

주요 변경 사항
- 기사 크롤링 하는 ArticleCrawler 클래스를 만들었습니다.
    - views.py에서 ArticleCrawler 를 이용하여 받은 기사 데이터를 db에 저장합니다 
- 프로젝트 setting에 logging 설정을 추가하였습니다.  이는 이후 필요한 곳에서 불러서 쓸 수 있습니다.
- 아직 예외처리나 코드 정리는 안 되어있습니다. 이후에 수정/추가하겠습니다. 

링크
- https://www.notion.so/45d469150a0f49d2b76fb4a60c777331?pvs=4

시급한 정도
- 🏃‍♂️ 보통 : 최대한 빠르게 리뷰 부탁드립니다. 

중점적으로 봐주었으면 하는 부분
- 없습니다

2023-05-03 11:22 UTC, gracia10 requested changes

2023-05-03 11:22 UTC, gracia10 commented on .gitignore
> +logs/
소스 내려받아서 서버를 실행할 경우 ValueError가 발생해 서버가 죽습니다 
/logs/drugstrore.log 파일이 없어 발생한 것 같은데 확인 부탁드립니다


Traceback (most recent call last):
  File "/Users/admin/.pyenv/versions/3.8.16/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Users/admin/.pyenv/versions/3.8.16/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    autoreload.raise_last_exception()
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 394, in execute
    autoreload.check_errors(django.setup)()
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/Users/admin/dev/VscodeProjects/drugstore/venv/lib/python3.8/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/Users/admin/.pyenv/versions/3.8.16/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/Users/admin/.pyenv/versions/3.8.16/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'file'

2023-05-03 11:22 UTC, gracia10 commented on apps/data_collection/articleCrawler.py
> +        'chosun' : 'https://search.daum.net/search?w=news&q=%EB%A7%88%EC%95%BD&DA=STC&spacing=0&period=d&sd={{startdate}}&ed={{enddate}}&cp=16d4PV266g2j-N3GYq&cpname=%EC%A1%B0%EC%84%A0%EC%9D%BC%EB%B3
수집 채널과 url 은  여러곳에서 사용되고 변경될 가능성도 높아서,
크롤러에 정의하기보단 앱 내에 constants.py 파일을 생성해 관리하는 것이 좋아 보입니다.

2023-05-03 11:22 UTC, gracia10 commented on apps/data_collection/articleCrawler.py
> +    def get_chosun_article(self, link:str) -> dict:
사이트별 기사를 긁어오는 메서드를 article_crawler 에 정의하면
한 소스파일에 코드라인 매우 길어집니다
crawler 폴더를 생성해
언론사별 크롤러 클래스를 만들고 호출하도록 개선하는 것을 추천드립니다.

2023-05-03 11:22 UTC, gracia10 commented on apps/data_collection/articleCrawler.py
> +from datetime import datetime, timedelta
파일 명칭은 스네이크로 변경해주세요 article_crawler

2023-05-03 11:28 UTC, gracia10 commented on apps/data_collection/articleCrawler.py
> +from datetime import datetime, timedelta
추가로 나중에 작업을 줄이기 위해
PEP 8 파이썬 표준 스타일 적용하여서 개발 진행해주시면 감사하겠습니다

2023-05-03 19:44 UTC, HyeM207 commented
### 1차 수정
**주요 변경 사항**
주신 comments 반영하여 전반적인 코드를 수정하였습니다
 -  [crawler] crawler 폴더 만들고, 언론사별 class화하여 크롤링 기능 세분화함
 -  [crawler] logging과 error handling 추가
 -  [crawler] 코드 PEP8 스타일 적용
-  [settings.py] 불필요한 주석 제거 및 logs 폴더 없을 시 생성 코드 추가
 -  [constants.py] 언론사 검색 url을 담은 딕셔너리를 상수화함
    
**링크**
- (없음)


**시급한 정도**
🐢 보통 :  5월 4일 오후 리뷰 전까지 부탁드립니다.


**중점적으로 봐주었으면 하는 부분**
- 없습니다

2023-05-04 02:24 UTC, gracia10 commented
테스트 코드는 차차 추가해봐요

2023-05-04 02:24 UTC, merged